import type { Locale } from "@/i18n/routing";

/**
 * The triage strings that are not generated by the model.
 *
 * Two sets of words survive every failure path and therefore have to exist in
 * both languages without going near Claude: the deterministic safety lines,
 * and the keyword matcher's explanations. Both are rendered on the server when
 * the API answers and in the browser when it cannot be reached, so the shape
 * below is what each side hands to `applySafetyFloor` and `triageProblem`.
 *
 * There is no English fallback baked into this file on purpose. `lib/ai` is
 * imported by the landing page bundle, and inlining a copy of the catalogue
 * here would ship every Nepali safety line to every English visitor — and,
 * worse, leave two places where the wording of "close the cylinder valve"
 * lives.
 */

export type SafetyCopy = {
  gas: string;
  burning: string;
  "live-wire": string;
  /** Shown when a photo was attached and nothing ever looked at it. */
  unseenPhoto: string;
};

export type TriageCopy = {
  safety: SafetyCopy;
  /** Keyword-rule key → explanation. See KEYWORD_RULES in mockTriage.ts. */
  explanations: Record<string, string>;
  /** Fallback category display name, for a slug we cannot resolve. */
  genericCategory: string;
  genericCtaLabel: string;
};

/** The two namespaces this needs, as they come out of the catalogue. */
type Messages = {
  safety: {
    gas: string;
    burning: string;
    liveWire: string;
    unseenPhoto: string;
  };
  fallback: Record<string, string>;
};

export function triageCopyFrom(messages: unknown): TriageCopy {
  const m = messages as Messages;
  return {
    safety: {
      gas: m.safety.gas,
      burning: m.safety.burning,
      "live-wire": m.safety.liveWire,
      unseenPhoto: m.safety.unseenPhoto,
    },
    explanations: m.fallback,
    genericCategory: m.fallback.genericCategory,
    genericCtaLabel: m.fallback.genericCtaLabel,
  };
}

/**
 * The language Claude is asked to answer in.
 *
 * The prompt itself stays English — it is instructions to a model, not copy —
 * but the explanation it returns is read by the person standing in the kitchen,
 * so it follows the interface.
 */
export const ANSWER_LANGUAGE: Record<Locale, string> = {
  en: "Always answer in English. The person is reading an English interface.",
  ne: "Always answer in Nepali, written in Devanagari — the person is reading a Nepali interface. Keep it plain and spoken, the way you would say it out loud to a neighbour, not formal written Nepali. Keep Rs amounts, brand names and trade loanwords people actually use (एसी, एमसीबी, इन्भर्टर, गिजर) as they are.",
};
