-- A multi-day job holds a site, not a slot.
--
-- THIS IS THE SENTENCE `ARCHITECTURE.md` USED TO NAME AS THE GAP: painting
-- occupies a room for four days and a painter for a few hours of each, because
-- putty dries, primer cures and coats need hours between them. Two holds, not
-- one, and they are different sizes:
--
--   * THE PROFESSIONAL is held for `working_minutes` ON EACH DAY of the run —
--     not the whole day, not the whole span. That is what retires painting's
--     `max_concurrent_jobs = 3`, which existed only to stop a painter being
--     blocked while the first job dried.
--   * THE SITE is held for the WHOLE span. A second job at the same address in
--     the same trade cannot be booked across it, because the room is full of
--     dust sheets whether or not anybody is standing in it.
--
-- The gap between the two is the drying. A painter is bookable on Tuesday
-- afternoon; the customer's living room is not. One number cannot say both.
--
-- A CHILD TABLE RATHER THAN DATE ARITHMETIC IN EVERY QUERY. It is generated by
-- a trigger from the parent, so it cannot drift, and it is the row a
-- professional will later be able to say "not Wednesday" against without the
-- parent booking having to carry a list.
--
-- NO ROWS EXIST TODAY AND THAT IS CORRECT. `spansDays()` refuses a span whose
-- duration is still `invented`, and all 36 sub-band durations are. Every job
-- therefore holds its minutes on a single day — exactly what every booking did
-- before this phase — until somebody does the research. The gate is mirrored
-- below and chained to `sub-band-durations` in LAUNCH-BLOCKERS.md.

create table if not exists public.booking_days (
  booking_id uuid not null references public.bookings (id) on delete cascade,
  -- The Nepal date this row is for. A date rather than a timestamp: the second
  -- day of a repaint is a day, not an instant, and pretending otherwise is how
  -- an invented 09:00 gets into the data.
  day date not null,
  -- Which day of the run, 1-based, so a screen can say "day 2 of 4" without
  -- re-deriving it from the span.
  day_index integer not null check (day_index >= 1),
  -- Minutes the professional is on the tools THAT DAY.
  working_minutes integer not null check (working_minutes > 0),
  -- THE TIME IS NULL ON EVERY DAY BUT THE FIRST, and deliberately. Day 1 is
  -- the slot the customer picked. Nobody has said when on day 3 the painter
  -- arrives, so nothing here claims to know — "sometime that day" is the
  -- honest answer and 09:00 would be a default presented as a fact.
  starts_at timestamptz,
  primary key (booking_id, day)
);

comment on table public.booking_days is
  'One row per day a multi-day job runs. The professional is held for working_minutes on each; the site is held for the whole span. Generated by a trigger from the parent booking, so the two cannot drift. Empty while every sub-band duration is still invented — see spansDays() and the multi-day-scheduling launch blocker.';
comment on column public.booking_days.starts_at is
  'Set on day 1 only, from the slot the customer picked. Null on later days because nobody has said when — an invented 09:00 would be a default presented as a measurement.';

alter table public.booking_days enable row level security;

-- Readable by the same people who can read the booking. No insert, update or
-- delete policy for anybody: these rows are the trigger's, and a caller who
-- could write them could hold a professional's week without booking anything.
drop policy if exists "Days follow their booking" on public.booking_days;
create policy "Days follow their booking"
  on public.booking_days for select
  to authenticated
  using (
    exists (
      select 1 from public.bookings b
      where b.id = booking_days.booking_id
        and (b.customer_id = auth.uid() or public.is_admin())
    )
  );

create index if not exists booking_days_day_idx on public.booking_days (day);

-- ---------------------------------------------------------------------------
-- Generated from the parent, never written by hand
-- ---------------------------------------------------------------------------

create or replace function public.sync_booking_days()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  span integer;
  publishable boolean;
  start_at timestamptz;
  minutes integer;
  per_day integer;
  i integer;
begin
  -- Only when something that shapes the run moves.
  if tg_op = 'UPDATE'
     and new.scheduled_for is not distinct from old.scheduled_for
     and new.band_slug is not distinct from old.band_slug
     and new.estimated_elapsed_days is not distinct from old.estimated_elapsed_days
     and new.provider_estimated_elapsed_days
         is not distinct from old.provider_estimated_elapsed_days
     and new.status is not distinct from old.status then
    return null;
  end if;

  delete from public.booking_days where booking_id = new.id;

  -- A job that is over holds nothing.
  if new.status in ('completed', 'cancelled', 'no_provider_found') then
    return null;
  end if;

  /*
   * THE PROVENANCE GATE, mirroring `spansDays()` in lib/booking/duration.ts.
   *
   * The professional's own figure is evidence — they have been to the site, so
   * their span stands whatever our sub-band says. OURS only spans days once
   * somebody has researched the duration, because holding four days of a
   * painter's week and four days of a customer's home off a guess takes real
   * bookable capacity, invisibly, and nothing on any screen tells it apart
   * from a measurement.
   */
  if new.provider_estimated_elapsed_days is not null then
    span := new.provider_estimated_elapsed_days;
  else
    select b.duration_source <> 'invented' into publishable
      from public.category_price_bands b
     where b.category_slug = new.category_slug
       and b.slug = new.band_slug;
    span := case when coalesce(publishable, false)
                 then coalesce(new.estimated_elapsed_days, 1)
                 else 1 end;
  end if;

  if span <= 1 then
    return null;
  end if;

  start_at := coalesce(new.scheduled_for, new.created_at, now());
  minutes := public.booking_working_minutes(
    new.estimated_working_minutes,
    new.provider_estimated_working_minutes
  );
  -- Spread evenly, at least a minute a day. A painter is not on the tools for
  -- the whole span — that is what the drying is — so the daily figure is the
  -- total divided by the days, not the total repeated.
  per_day := greatest(1, minutes / span);

  for i in 1..span loop
    insert into public.booking_days
      (booking_id, day, day_index, working_minutes, starts_at)
    values (
      new.id,
      -- Nepal Time is UTC+05:45, fixed year-round — same arithmetic as
      -- NPT_OFFSET_MINUTES in lib/booking/schedule.ts.
      ((start_at + interval '5 hours 45 minutes') + make_interval(days => i - 1))::date,
      i,
      per_day,
      case when i = 1 then start_at else null end
    );
  end loop;

  return null;
end;
$$;

comment on function public.sync_booking_days() is
  'Regenerates booking_days from the parent whenever the run changes shape. Refuses to span days on a duration nobody researched, mirroring spansDays() in lib/booking/duration.ts.';

revoke execute on function public.sync_booking_days() from public, anon, authenticated;

-- AFTER, not BEFORE: it writes child rows and needs the parent to exist.
drop trigger if exists bookings_sync_days on public.bookings;
create trigger bookings_sync_days
  after insert or update on public.bookings
  for each row execute function public.sync_booking_days();

-- ---------------------------------------------------------------------------
-- The site's own hold
-- ---------------------------------------------------------------------------

create or replace function public.enforce_site_capacity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  /*
   * ONE TRADE AT A TIME IN ONE HOME. Two painters in the same living room on
   * overlapping days is not a scheduling nicety — the second customer's
   * booking cannot physically happen. A DIFFERENT trade is fine and
   * deliberately allowed: an electrician can work around a painter.
   *
   * Checked against booking_days, so it only bites on a job that actually
   * spans days. A same-day job is already covered by the professional's own
   * window in `enforce_slot_capacity`.
   */
  if exists (
    select 1
    from public.booking_days mine
    join public.booking_days theirs on theirs.day = mine.day
    join public.bookings other on other.id = theirs.booking_id
    where mine.booking_id = new.booking_id
      and other.id <> new.booking_id
      and other.status in ('pending', 'accepted', 'en_route', 'in_progress')
      and other.address_id = (
        select b.address_id from public.bookings b where b.id = new.booking_id
      )
      and other.category_slug = (
        select b.category_slug from public.bookings b where b.id = new.booking_id
      )
  ) then
    raise exception 'That address already has this trade booked on one of those days'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke execute on function public.enforce_site_capacity() from public, anon, authenticated;

drop trigger if exists booking_days_enforce_site on public.booking_days;
create trigger booking_days_enforce_site
  after insert on public.booking_days
  for each row execute function public.enforce_site_capacity();
